const VERSION="YepTennis Simple 1.1",HOST="tennis-api-atp-wta-itf.p.rapidapi.com",BASE=`https://${HOST}`;const TTL={rankings:86400,calendar:86400,results:86400,news:21600};
const json=(d,s=200)=>new Response(JSON.stringify(d),{status:s,headers:{"content-type":"application/json;charset=utf-8","cache-control":"no-store"}});
async function api(path,env){if(!env.TENNIS_API_KEY)throw Error("TENNIS_API_KEY is not configured in Cloudflare.");const r=await fetch(BASE+path,{headers:{"X-RapidAPI-Key":env.TENNIS_API_KEY,"X-RapidAPI-Host":HOST}}),t=await r.text();let d={};try{d=JSON.parse(t)}catch{}if(!r.ok)throw Error(d.message||d.error||`Tennis API HTTP ${r.status}`);if(d?.error)throw Error(String(d.error));return d}
function arr(d,keys=[]){if(Array.isArray(d))return d;for(const k of ["data","results","items",...keys])if(Array.isArray(d?.[k]))return d[k];return[]}
async function cached(env,key,ttl,fn){if(env.TENNIS_CACHE){try{const x=await env.TENNIS_CACHE.get(key,"json");if(x)return x}catch{}}const x=await fn();if(env.TENNIS_CACHE){try{await env.TENNIS_CACHE.put(key,JSON.stringify(x),{expirationTtl:ttl})}catch{}}return x}
const player=p=>({id:p?.id??p?.playerId??null,name:p?.name??p?.playerName??p?.fullName??"Unknown",country:p?.countryAcr??p?.countryCode??p?.country??""});
function rankRow(r,i){const p=r?.player&&typeof r.player==='object'?r.player:r;return {...player(p),rank:Number(r?.position??r?.rank??i+1),points:Number(r?.rankingPoints??r?.point??r?.points??0)}}
async function rankings(env,tour){return cached(env,`simple:rankings:${tour}`,TTL.rankings,async()=>{const d=await api(`/tennis/v2/${tour}/ranking/singles?pageNo=1&pageSize=50`,env);return{tour,players:arr(d,["rankings"]).map(rankRow).filter(x=>x.name!=="Unknown")}})}
function category(t,tour){const s=[t?.tier,t?.rank?.name,t?.rankName,t?.category,t?.level,t?.type,t?.name].filter(Boolean).join(" ").toLowerCase();if(s.includes("grand slam")||/wimbledon|roland garros|french open|us open|australian open/i.test(s))return"Grand Slam";if(/masters\s*1000|masters series|\b1000\b/.test(s))return tour.toUpperCase()+" 1000";if(/\b500\b/.test(s))return tour.toUpperCase()+" 500";if(/\b250\b/.test(s))return tour.toUpperCase()+" 250";return""}
function normT(t,tour){return{id:t?.id??t?.seasonId??t?.tournamentId??null,name:t?.name??t?.tournamentName??"Tournament",tour:tour.toUpperCase(),category:category(t,tour),date:t?.date??t?.startDate??t?.start??"",endDate:t?.endDate??t?.dateTo??t?.end??"",country:t?.country?.name??t?.countryName??t?.country?.code??"",surface:t?.court?.name??t?.surface??t?.surfaceName??""}}
async function calendar(env){return cached(env,`simple:calendar:${new Date().getUTCFullYear()}`,TTL.calendar,async()=>{const a=await api(`/tennis/v2/atp/tournament/calendar/${new Date().getUTCFullYear()}?pageNo=1&pageSize=200`,env),w=await api(`/tennis/v2/wta/tournament/calendar/${new Date().getUTCFullYear()}?pageNo=1&pageSize=200`,env),aa=arr(a,["tournaments"]),ww=arr(w,["tournaments"]);return{tournaments:[...aa.map(x=>normT(x,"atp")),...ww.map(x=>normT(x,"wta"))].filter(x=>x.category)}})}
const result=(r,tour)=>({id:r?.matchId??r?.id??null,date:r?.date??r?.startTime??"",tour:tour.toUpperCase(),tournament:r?.tournament?.name??r?.tournamentName??"Tournament",tournamentId:r?.tournament?.id??r?.tournamentId??null,round:r?.round?.name??r?.roundName??r?.round??"",winner:player(r?.player1??r?.winner),loser:player(r?.player2??r?.loser),score:r?.result??r?.score??""});
async function results(env,date){if(!/^\d{4}-\d{2}-\d{2}$/.test(date))throw Error("Date must be YYYY-MM-DD.");return cached(env,`simple:results:${date}`,TTL.results,async()=>{const[a,w]=await Promise.all([api(`/tennis/v2/atp/results/${date}?pageNo=1&pageSize=500&filter=PlayerGroup:singles`,env),api(`/tennis/v2/wta/results/${date}?pageNo=1&pageSize=500&filter=PlayerGroup:singles`,env)]);return{date,results:[...arr(a).map(x=>result(x,"atp")),...arr(w).map(x=>result(x,"wta"))]}})}
function strip(s){return String(s||"").replace(/<!\[CDATA\[([\s\S]*?)\]\]>/g,"$1").replace(/<[^>]+>/g,"").replace(/&amp;/g,"&").replace(/&quot;/g,'"').replace(/&#39;/g,"'").trim()}
function rss(xml,source){return(xml.match(/<item[\s\S]*?<\/item>/gi)||[]).map(i=>{const g=t=>strip((i.match(new RegExp(`<${t}[^>]*>([\\s\\S]*?)<\\/${t}>`,`i`))||[])[1]||"");const l=strip((i.match(/<link>([\s\S]*?)<\/link>/i)||[])[1]||"");const m=i.match(/<media:(?:content|thumbnail)[^>]+url=["']([^"']+)["']/i),e=i.match(/<enclosure[^>]+url=["']([^"']+)["']/i);return{title:g("title"),link:l,description:g("description"),date:g("pubDate"),image:m?.[1]||e?.[1]||"",source}}).filter(x=>x.title&&x.link)}
async function news(env){return cached(env,"simple:news",TTL.news,async()=>{const out=[];for(const [u,s] of [["https://feeds.bbci.co.uk/sport/tennis/rss.xml","BBC Sport"],["https://www.atptour.com/en/media/rss-feed/xml-feed","ATP Tour"]])try{const r=await fetch(u,{headers:{"User-Agent":"YepTennis/1.0"}});if(r.ok)out.push(...rss(await r.text(),s))}catch{}out.sort((a,b)=>new Date(b.date||0)-new Date(a.date||0));return{items:out.slice(0,30)}})}
export default{async scheduled(c,e,ctx){ctx.waitUntil(Promise.all([rankings(e,"atp"),rankings(e,"wta"),calendar(e),results(e,new Date().toISOString().slice(0,10)),news(e)]).catch(()=>{}))},async fetch(req,e){const u=new URL(req.url);try{if(u.pathname==="/api/health")return json({ok:true,version:VERSION,apiConfigured:!!e.TENNIS_API_KEY,kvConfigured:!!e.TENNIS_CACHE});if(u.pathname==="/api/rankings"){const t=u.searchParams.get("tour")==="wta"?"wta":"atp";return json(await rankings(e,t))}if(u.pathname==="/api/player"){const t=u.searchParams.get("tour")==="wta"?"wta":"atp",id=u.searchParams.get("id");if(!id)return json({error:"Missing player id."},400);const d=await rankings(e,t),p=d.players.find(x=>String(x.id)===String(id));return json(p?{found:true,player:{...p,summary:`${p.name} is currently ranked #${p.rank} in the ${t.toUpperCase()} rankings with ${p.points.toLocaleString()} points.`}}:{found:false,message:"Player not found in the current Top 50."})}if(u.pathname==="/api/results")return json(await results(e,u.searchParams.get("date")||new Date().toISOString().slice(0,10)));if(u.pathname==="/api/calendar"){const d=await calendar(e),today=new Date().toISOString().slice(0,10);return json({tournaments:d.tournaments.filter(x=>x.date&&x.date.slice(0,10)>=today).sort((a,b)=>a.date.localeCompare(b.date)).slice(0,20)})}if(u.pathname==="/api/news")return json(await news(e));if(u.pathname.startsWith("/api/"))return json({error:"API endpoint not found",version:VERSION,path:u.pathname},404);return e.ASSETS.fetch(req)}catch(err){return json({error:err?.message||"API error",version:VERSION},500)}}};